"""Update models with proper typing

Revision ID: 5658704f7c4c
Revises: 0ede583bc5bd
Create Date: 2025-09-17 14:10:50.847622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5658704f7c4c'
down_revision: Union[str, Sequence[str], None] = '0ede583bc5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_submissions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessment_submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessment_submissions', 'responses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('assessment_submissions', 'tier_used',
               existing_type=postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', name='tierenum'),
               nullable=False)
    op.alter_column('assessment_submissions', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('assessment_submissions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assessments', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assessments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dimensions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dimensions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dimensions', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dimensions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'dimension_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=postgresql.ENUM('MULTIPLE_CHOICE', 'SCALE', 'BOOLEAN', 'TEXT', name='questiontypeenum'),
               nullable=False)
    op.alter_column('questions', 'required_tier',
               existing_type=postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', name='tierenum'),
               nullable=False)
    op.alter_column('questions', 'scoring_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'scoring_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('questions', 'required_tier',
               existing_type=postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', name='tierenum'),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=postgresql.ENUM('MULTIPLE_CHOICE', 'SCALE', 'BOOLEAN', 'TEXT', name='questiontypeenum'),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'dimension_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dimensions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dimensions', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('dimensions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dimensions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('assessments', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assessments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assessment_submissions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_submissions', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('assessment_submissions', 'tier_used',
               existing_type=postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', name='tierenum'),
               nullable=True)
    op.alter_column('assessment_submissions', 'responses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('assessment_submissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assessment_submissions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
